#!/usr/bin/env python3
"""
Email notification example using the collected Sina 7x24 news data
"""

import json
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import os

def send_news_email(json_file_path, smtp_config):
    """
    Send collected news as email notification
    
    Args:
        json_file_path: Path to the JSON file with collected news
        smtp_config: Dictionary with SMTP configuration
    """
    # Load the collected news data
    with open(json_file_path, 'r', encoding='utf-8') as f:
        news_data = json.load(f)
    
    # Create email content
    subject = f"Sina 7x24 Financial News - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    
    # Create HTML email body
    html_body = f"""
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Sina 7x24 Financial News</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 20px; }}
            .category {{ margin-bottom: 20px; padding: 10px; border-left: 4px solid #007cba; }}
            .news-item {{ margin: 10px 0; padding: 8px; background-color: #f9f9f9; }}
            .time {{ color: #666; font-size: 0.9em; }}
            .content {{ margin-top: 5px; }}
            h2 {{ color: #007cba; border-bottom: 2px solid #007cba; padding-bottom: 5px; }}
        </style>
    </head>
    <body>
        <h1>Sina 7x24 Financial News Summary</h1>
        <p><strong>Collection Time:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        <p><strong>Total Categories:</strong> {len(news_data)}</p>
        <p><strong>Total News Items:</strong> {sum(len(items) for items in news_data.values())}</p>
        
    """
    
    # Add news by category
    for category, items in news_data.items():
        if items:  # Only include categories with items
            html_body += f"""
        <div class="category">
            <h2>{category} ({len(items)} items)</h2>
            {''.join([
                f'''<div class="news-item">
                    <div class="time">[{item['time']}]</div>
                    <div class="content">{item['content']}</div>
                    <div><a href="{item['link_preview']}" target="_blank">View Full Article</a></div>
                </div>''' 
                for item in items
            ])}
        </div>
        """
    
    html_body += """
        <hr>
        <p><small>This email was automatically generated by Sina 7x24 News Collector</small></p>
    </body>
    </html>
    """
    
    # Create message
    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = smtp_config['sender_email']
    msg['To'] = smtp_config['recipient_email']
    
    # Attach HTML content
    html_part = MIMEText(html_body, 'html', 'utf-8')
    msg.attach(html_part)
    
    # Send email
    try:
        server = smtplib.SMTP(smtp_config['smtp_server'], smtp_config['smtp_port'])
        server.starttls()
        server.login(smtp_config['sender_email'], smtp_config['sender_password'])
        
        server.send_message(msg)
        server.quit()
        
        print(f"✅ Email notification sent successfully!")
        print(f"📄 Subject: {subject}")
        print(f"📬 To: {smtp_config['recipient_email']}")
        return True
        
    except Exception as e:
        print(f"❌ Failed to send email: {str(e)}")
        return False

def main():
    """Example usage of email notification"""
    print("📧 Sina 7x24 News Email Notification Example")
    print("=" * 50)
    
    # Find the most recent JSON file
    import glob
    json_files = glob.glob("simplified_example_*.json")
    if not json_files:
        print("❌ No JSON files found. Run the collector first.")
        return
    
    latest_file = max(json_files, key=os.path.getctime)
    print(f"📊 Using data from: {latest_file}")
    
    # Example SMTP configuration
    # In real usage, these would come from environment variables
    smtp_config = {
        'smtp_server': os.getenv('SMTP_SERVER', 'smtp.gmail.com'),
        'smtp_port': int(os.getenv('SMTP_PORT', '587')),
        'sender_email': os.getenv('SENDER_EMAIL', ''),
        'sender_password': os.getenv('SENDER_PASSWORD', ''),
        'recipient_email': os.getenv('RECIPIENT_EMAIL', '')
    }
    
    # Show what would be sent (without actually sending)
    with open(latest_file, 'r', encoding='utf-8') as f:
        news_data = json.load(f)
    
    print(f"📈 Categories covered: {len(news_data)}")
    print(f"📰 Total news items: {sum(len(items) for items in news_data.values())}")
    
    for category, items in news_data.items():
        print(f"  • {category}: {len(items)} items")
    
    print("\n💡 To enable email notifications:")
    print("   1. Set environment variables: SENDER_EMAIL, SENDER_PASSWORD, RECIPIENT_EMAIL")
    print("   2. Update SMTP configuration as needed")
    print("   3. Uncomment the send_news_email() call in your workflow")
    
    # Uncomment the following lines to actually send an email (requires valid credentials):
    # if smtp_config['sender_email'] and smtp_config['sender_password'] and smtp_config['recipient_email']:
    #     success = send_news_email(latest_file, smtp_config)
    #     if success:
    #         print("🎉 Email notification workflow completed successfully!")
    # else:
    #     print("\n⚠️  Email credentials not configured - skipping email send")

if __name__ == "__main__":
    main()